spring.application.name=drive_only_server
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://driveonly-db.chawsmksyj5c.ap-northeast-2.rds.amazonaws.com:3306/driveonly_db
spring.datasource.username = minjun
spring.datasource.password = driveonly123!!
